name: Release Build

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish to NuGet
    environment: nuget
    env:
      solution-path: './src/NetCore.Utilities.Spreadsheet.sln'
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Ensure .NET Installed
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.0.5'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.1
      with:
        useConfigFile: true
      
    - name: Restore Packages
      run: dotnet restore "${{ env.solution-path }}"
    - name: Build
      run: dotnet build "${{ env.solution-path }}" --no-restore --configuration Release -p:version=${{ steps.gitversion.outputs.majorMinorPatch }}
    - name: Test
      run: dotnet test "${{ env.solution-path }}" --no-build --configuration Release
    
    - name: Publish
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.ICG_NUGET_API_KEY }}
