name: Release Build

on:
  push:
    tags: 
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish to NuGet
    environment: nuget
    env:
      solution-path: './src/NetCore.Utilities.Spreadsheet.sln'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0

    - name: Ensure .NET Installed
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 9.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
      with:
        versionSpec: '6.4.0'
  
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@bc6623af8fc07d5a8903052dd46da33403eec8e8 # v4.5.0
      
    - name: Restore Packages
      run: dotnet restore "${{ env.solution-path }}"
    - name: Build
      run: dotnet build "${{ env.solution-path }}" --no-restore --configuration Release -p:version=${{ steps.gitversion.outputs.majorMinorPatch }}
    - name: Test
      run: dotnet test "${{ env.solution-path }}" --no-build --configuration Release
    
    - name: Publish
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.ICG_NUGET_API_KEY }}
